# 工作流名称
name: Build Electron App

# 触发条件：手动触发和 push 到 master 分支
on:
  workflow_dispatch:
  push:
    branches: [ master ]

# 工作任务
jobs:
  # 构建 Windows 版本
  build-windows:
    runs-on: windows-latest
    steps:
      # 检出代码
      - uses: actions/checkout@v4
      
      # 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      # 安装依赖
      - name: Install dependencies
        run: npm install
      
      # 构建应用
      - name: Build application
        run: npm run make
      
      # 上传构建产物
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: out/make/**/*.zip
      
      # 发布
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: out/make/**/*.zip

  # 构建 macOS 版本
  build-macos:
    runs-on: macos-14
    steps:
      # 检出代码
      - uses: actions/checkout@v4
      
      # 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      # 安装依赖
      - name: Install dependencies
        run: npm install
      
      # 构建应用
      - name: Build application
        run: npm run make
      
      # 上传构建产物
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: out/make/**/*.zip

      # 发布
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: out/make/**/*.zip